#!/bin/bash

# shortcut to modern tool
alias ls="eza --icons --group-directories-first"
alias lg="lazygit"
alias lzd="lazydocker"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -h' # human-reader sizes

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# simple fuzzy open with nvim
alias v='nvim "$(fzf --preview "bat --style=numbers --color=always --line-range :50 {}")"'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# frequent command
alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias sys-suspend='sudo pm-suspend'

# reload zsh
alias zshreload='source ~/.config/zsh/.zshrc'

# get port
alias port="netstat -tulpn | grep"

# quick config path
alias zshconfig="nvim ~/.config/zsh/.zshrc"
alias tmuxconfig='nvim ~/.config/tmux/tmux.conf'
