#!/bin/sh

# shortcut to modern tool
alias ls="exa"
alias lg="lazygit"
alias lzd="lazydocker"
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -h'                      # human-reader sizes

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# command put stuff to nvim
alias v='nvim "$(fd --type f --hidden --exclude .git | fzf)"'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# frequent command
alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias sys-suspend='sudo pm-suspend'

# reload zsh
alias zshreload='source ~/.config/zsh/.zshrc'

# get port
alias port="netstat -tulpn | grep"

# x11
alias xpropc='xprop | grep WM_CLASS'

# grap emoji from fzf
alias emoj='emoji-fzf preview | fzf -m --preview "emoji-fzf get --name {1}" | cut -d " " -f 1 | emoji-fzf get'

# Copy using clip
alias copy='xclip -sel clip'

# cool scripts
alias source-setup="source $HOME/Documents/scripts/sourceSetup.sh"
alias debian-ubuntu-cleanup="source $HOME/Documents/scripts/debian-ubuntu-clean.sh"

# quick config path
alias zshconfig="~/.config/zsh/ && nvim"
alias alacrittyconfig="nvim ~/.config/alacritty/alacritty.toml"
alias i3config='nvim ~/.config/i3/config'
alias tmuxconfig='nvim ~/.config/tmux/tmux.conf'
alias i3statusrs_config='nvim ~/.config/i3status-rust/config.toml'
alias picomconfig='nvim ~/.config/picom/picom.conf'
