#!/bin/sh

export HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="$PATH:/usr/local/go/bin"
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/fnm:$PATH
export PATH="$HOME/.bun/bin":$PATH
export PATH="$HOME/go/bin":$PATH
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
if [[ ! "$PATH" == */home/knock-huynh/.fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}/home/knock-huynh/.fzf/bin"
fi
eval "$(fnm env --use-on-cd)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh --cmd j)"
eval "$(atuin init zsh)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
eval "$(fzf --zsh)"
