#!/usr/bin/zsh

# shortcut to modern tool
alias lg="lazygit"
alias lzd="lazydocker"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h' # human-readable sizes

# get top process eating memory
alias psmem='ps aux -o pid,comm,pmem | sort -nr -k 3 | head -6'

# get top process eating cpu
alias pscpu='ps aux -o pid,comm,pcpu | sort -nr -k 3 | head -6'

# open with nvim
alias v='nvim'
alias p='fzf --preview "bat --style=numbers --color=always --line-range :500 {}"'

# choose open sessions
alias tsa="~/dotfiles/scripts/tmux-sesh.sh"

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# reload zsh
alias zshreload='source ~/.config/zsh/.zshrc'

# get port
alias port="lsof -i -P | grep"

# quick config path
alias zshconfig="nvim ~/.config/zsh/.zshrc"
alias tmuxconfig='nvim ~/.config/tmux/tmux.conf'

# today note
alias ot="nvim '+Obsidian today'"
