# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

icons_format = "{icon}"

[theme]
theme = "nord-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome"
#[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "


[[block]]
block = "cpu"

[[block]]
block = "memory"
format_alt = " $icon_swap $swap_free.eng(3,B,M)/$swap_total.eng(3,B,M)($swap_used_percents.eng(2)) "
interval = 30
warning_mem = 70
critical_mem = 90


[[block]]
block = "net"
format = " $icon $ip "

[[block]]
block = "sound"
device_kind = "source"
format = " $icon { $volume|} "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
format = " $icon { $volume|} "
headphones_indicator=true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
locale = "vi_VN"
[block.format]
full = " $icon %d/%m %R "
short = " $icon %R "

[[block]]
block = "battery"
format = "$icon $percentage"

[[block]]
block = "menu"
text = ""
[[block.items]]
display = " -&gt;  &lt;-"
cmd = "i3 exit"
confirm_msg = "Are you sure you want to log out?"
[[block.items]]
display = " -&gt;  &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
