# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

icons_format = "{icon}"

[theme]
theme = "tokyo_night.toml"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

[[block]]
block = "net"
format = " $icon $device"
format_alt = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device at $ip"

[[block]]
block = "sound"
format = " $icon { $volume|} "
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "custom"
command = "~/Documents/scripts/fcitx-status.sh"
interval = 1

[[block]]
block = "time"
