// codebase-memory-mcp:start
// Generated by codebase-memory-mcp for OpenCode.
// Regenerated on install/update from the MCP tool registry, so it cannot
// drift from the tools the server actually serves. Edits inside this block
// are overwritten; edit outside it, or remove the markers to take ownership.
// OpenCode already reaches every tool over MCP; this adds only the
// automatic graph lookup before a grep/glob, which other clients get
// through their own hook configuration.
//
// V2 loads a plugin from its default export: an object with `id` and `setup`.
// Do not import `@opencode/plugin` here: the stow symlink makes it unresolvable.
import { spawn } from 'node:child_process';

const BIN = '/Users/ht2knock/.local/bin/codebase-memory-mcp';

function augment(tool, args) {
  return new Promise((resolve) => {
    const child = spawn(BIN, ['hook-augment'], {
      stdio: ['pipe', 'pipe', 'ignore'],
      env: { ...process.env, CBM_LOG_LEVEL: 'error' },
    });
    let out = '';
    child.stdout.on('data', (d) => (out += d.toString()));
    child.on('error', () => resolve(''));
    child.on('close', () => resolve(out));
    child.stdin.end(JSON.stringify({
      hook_event_name: 'PreToolUse',
      tool_name: tool,
      tool_input: args ?? {},
    }));
  });
}

export default {
  id: 'codebase-memory-mcp',
  async setup(ctx) {
    await ctx.tool.hook('execute.after', async (event) => {
      if (event.status !== 'completed') return;
      const tool = event.tool === 'grep' ? 'Grep' : event.tool === 'glob' ? 'Glob' : null;
      if (!tool) return;
      const extra = await augment(tool, event.input);
      if (!extra) return;
      const content = event.result.content;
      if (typeof content === 'string') {
        event.result = { ...event.result, content: `${content}\n${extra}` };
      } else if (Array.isArray(content)) {
        event.result = { ...event.result, content: [...content, { type: 'text', text: extra }] };
      }
    });
  },
};
// codebase-memory-mcp:end
