[[mgr.prepend_keymap]]
desc = 'Back to current cwd'
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures/walle/images"
desc = "Cd to ~/Pictures"
