return {
  {
    'nvim-treesitter/nvim-treesitter',
    branch = 'main',
    build = ':TSUpdate',
    dependencies = {
      'nvim-treesitter/nvim-treesitter-context',
      'nvim-treesitter/nvim-treesitter-textobjects',
    },
    ensure_installed = {
      'bash',
      'c',
      'go',
      'astro',
      'typescript',
      'javascript',
      'diff',
      'html',
      'css',
      'lua',
      'tsx',
      'json',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'vim',
      'vimdoc',
      'python',
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
    fold = { enable = true },
    incremental_selection = { enable = true },
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
        keymaps = {
          ['af'] = '@function.outer',
          ['if'] = '@function.inner',
          ['ac'] = '@class.outer',
          ['ic'] = '@class.inner',
          ['aa'] = '@parameter.outer',
          ['ia'] = '@parameter.inner',
          ['ai'] = '@conditional.inner',
          ['al'] = '@loop.inner',
        },
      },
    },
  },
}
